
CREATE SEQUENCE SEQ_POST;


CREATE TABLE TBL_POST(
    ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
    POST_TITLE VARCHAR2(255) NOT NULL,
    POST_CONTENT VARCHAR2(255) NOT NULL,
    POST_READ_COUNT NUMBER DEFAULT 0,
    STATUS NUMBER DEFAULT 0,
    CREATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM TBL_POST;



